POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQHRlc3QuY29tIiwiZXhwIjoxNzA2NTgxMzQ3LCJpZCI6MX0.0gWeER3-RkkUALIJ80cbXhfM_dqP-nSxXuRXPLsCQ0A

{
    "name": "Event 1",
    "description": "Event 1 description",
    "location": "Event 1 location",
    "datetime": "2024-07-29T00:00:00.000Z"
}
